repos:
  # Autoformat: YAML, JSON, Markdown, etc.
  - repo: https://github.com/pycontribs/mirrors-prettier
    rev: v3.3.3
    hooks:
      - id: prettier
        args: [--ignore-unknown]

  # Lint: Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        args: [--fix, --ignore, docs/techdoc]
