site_name: HOTOSM Docs
site_description: Documentation index across HOTOSM tools.
# strict: true
site_url: "https://www.hotosm.org"

repo_name: "hotosm/docs"
repo_url: "https://github.com/hotosm/docs/"
edit_uri: "edit/main/docs/"

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/hotosm/"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/hotosm"
    - icon: "fontawesome/solid/globe"
      link: "https://www.hotosm.org"

theme:
  name: material
  palette:
    primary: custom

extra_css:
  - css/extra.css

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.emoji:
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - exclude:
      glob:
        - plugins/*
        - __pycache__/*
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true

nav:
  - Home: index.md
  - Services:
      - FMTM: https://hotosm.github.io/fmtm/
  - Python Libs:
      - OSM Fieldwork: https://hotosm.github.io/osm-fieldwork/
      - OSM RawData: https://hotosm.github.io/osm-rawdata/
      - OSM Login: https://hotosm.github.io/osm-login-python/
      - FMTM Splitter: https://hotosm.github.io/fmtm-splitter/
  - UI / Design:
      - UI Components: https://hotosm.github.io/shared-ui-components/
      - Map Component: https://hotosm.github.io/shared-map-components/
