site_name: HOTOSM Docs
site_description: Documentation index across HOT's tools.
# strict: true
site_url: "https://www.hotosm.org"

repo_name: "hotosm/docs"
repo_url: "https://github.com/hotosm/docs/"
edit_uri: "edit/main/docs/"

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/hotosm/"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/hotosm"
    - icon: "fontawesome/solid/globe"
      link: "https://www.hotosm.org"
  copyright: Copyright &copy; 2010 HOTOSM
  generator: false

theme:
  name: material
  palette:
    primary: custom
  favicon: assets/images/favicon.png
  logo: assets/images/hot_logo.png
  # custom_dir: docs/overrides
  features:
    - navigation.instant

extra_css:
  - css/extra.css

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.emoji:
  - pymdownx.tabbed:
      alternate_style: true
  - mdx_truly_sane_lists

plugins:
  - search
  - drawio

nav:
  - Home: index.md
  - Become a Contributor: become-a-contributor.md
  - Projects:
      - Intro: projects/tools-summary.md
      - Tasking Manager:
          - Docs: https://hotosm.github.io/tasking-manager/
          - Roadmap: https://github.com/hotosm/tasking-manager/tree/main?tab=readme-ov-file#product-roadmap
          - Dev Roadmap: https://github.com/orgs/hotosm/projects/28
          - Task Tracker: https://github.com/orgs/hotosm/projects/14/views/2
      - Field Mapping TM (FMTM):
          - Landing Page: https://fmtm.dev
          - About: techdoc/overview/FMTMProductPitch.pdf
          - Docs: https://docs.fmtm.dev
          - Roadmap: https://github.com/hotosm/fmtm/tree/main?tab=readme-ov-file#roadmap
          - Dev Roadmap: https://roadmap.fmtm.dev
          - Field Pilots:
              - Monrovia: projects/FMTM/Monrovia E2E Request.pdf
      - Drone TM:
          - Repo: https://github.com/hotosm/drone-tm
          - Docs: https://hotosm.github.io/drone-tm
          - Roadmap: https://github.com/hotosm/drone-tm/tree/main?tab=readme-ov-file#roadmap
          - Dev Roadmap: https://github.com/orgs/hotosm/projects/39
      - fAIr:
          - Overview: techdoc/overview/fAIrProductPitch.pdf
          - Docs: https://fair-dev.hotosm.org/
          - Roadmap: https://github.com/hotosm/fair/tree/main?tab=readme-ov-file#product-roadmap
          - Dev Roadmap: https://github.com/orgs/hotosm/projects/30/views/1
          - Task Tracker: https://github.com/orgs/hotosm/projects/30/views/2
      - OpenAerialMap:
          - Overview: projects/openaerialmap.md
      - Export Tool:
          - Docs: https://export.hotosm.org/v3/learn
          - Roadmap: https://github.com/hotosm/osm-export-tool/tree/master?tab=readme-ov-file#product-roadmap
          - Task Tracker: https://github.com/orgs/hotosm/projects/29
      - Raw Data API:
          - Docs: https://hotosm.github.io/raw-data-api/
          - Roadmap: https://github.com/hotosm/raw-data-api/tree/master?tab=readme-ov-file#product-roadmap
          - Task Tracker: https://github.com/orgs/hotosm/projects/29
      - Diagrams: diagrams.md
      - End-to-End Workflow: https://hotosm.github.io/e2e-mapping
  - Modularization:
      - Info: modules.md
      - Backend: modules/backend.md
      - Frontend: modules/frontend.md
      - UI / Design:
          - UI Components: https://hotosm.github.io/ui/
      - Python Modules:
          - OSM Fieldwork: https://hotosm.github.io/osm-fieldwork/
          - OSM RawData: https://hotosm.github.io/osm-rawdata/
          - OSM Merge: https://hotosm.github.io/osm-merge/
          - OSM Login: https://hotosm.github.io/osm-login-python/
          - FMTM Splitter: https://hotosm.github.io/fmtm-splitter/
          - fAIr Utilities: https://hotosm.github.io/fAIr-utilities/
  - Developer Guide:
      - Intro: dev-guide/intro.md
      - Managing Repos:
          - Git: dev-guide/repo-management/git.md
          - Pre-Commit: dev-guide/repo-management/pre-commit.md
          - Version Control: dev-guide/repo-management/version-control.md
          - Dependency Management: dev-guide/repo-management/dependencies.md
          - Licensing: dev-guide/repo-management/licensing.md
      - Web Development:
          - Backend: dev-guide/web-backend.md
          - Frontend: dev-guide/web-frontend.md
          - Accessibility: dev-guide/accessibility.md
      - Testing: dev-guide/testing.md
      - Documentation:
          - Intro: techdoc/README.md
          - Automatically Generated Docs: dev-guide/api-doc-gen.md
          - Diátaxis Framework: https://diataxis.fr
      - Containers:
          - Intro: dev-guide/containers/containers-101.md
          # - Cheat Sheet: dev-guide/containers/containers-cheat-sheet.md
          - Local Kubernetes: dev-guide/containers/kubernetes-local-kind.md
          - Production DB: dev-guide/containers/production-db.md
  - DevOps:
      - Reusable Workflows: https://hotosm.github.io/gh-workflows/
  - Our Development Practices: dev-practices.md
  - Code of Conduct: code-of-conduct.md
  - Privacy Policy: https://www.hotosm.org/privacy.html
