[project]
name = "docs"
dynamic = ["version"]
description = "Documentation index across HOTOSM tools."
authors = [
    {name = "Sam Woodcock", email = "sam.woodcock@hotosm.org"},
]
dependencies = [
    "mkdocs>=1.5.2",
    "mkdocs-material>=9.2.3",
    "mkdocstrings-python>=1.5.1",
    "mkdocs-exclude>=1.0.2",
]
requires-python = ">=3.10"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["hot", "hotosm", "docs", "documentation", "humanitarian"]

[project.urls]
homepage = "https://hotosm.github.io/docs"
documentation = "https://hotosm.github.io/docs"
repository = "https://github.com/hotosm/docs"

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.0"
version_files = [
    "pyproject.toml:version",
]
